# Generated by Django 4.2.28 on 2026-05-02 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('bakery', 'Bakery'), ('catering', 'Catering Service'), ('ghost-kitchen', 'Ghost Kitchen'), ('food-truck', 'Food Truck')], max_length=20)),
                ('location', models.CharField(max_length=120)),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity_offer', models.DecimalField(blank=True, decimal_places=2, help_text='Optional percentage of equity offered to investors.', max_digits=5, null=True)),
                ('summary', models.CharField(max_length=220)),
                ('story', models.TextField()),
                ('use_of_funds', models.TextField()),
                ('target_timeline', models.CharField(max_length=120)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
